// This file is generated by Tools/cases_generator/generate_cases.py
// from:
//   Python/bytecodes.c
// Do not edit!
#define OPS(instr, ...) \
    instr(buffer, pos, buffer_size); \

#define OP(instr, ...) \
    OP_##instr(__VA_ARGS__ __VA_OPT__(,) buffer, pos, buffer_size); \

#define ARG(...) \
    __VA_ARGS__ \


        TARGET(NOP) {
            OP(NOP);
            DISPATCH();
        }

        TARGET(RESUME) {
            OP(RESUME, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_RESUME) {
            OP(INSTRUMENTED_RESUME, oparg);
            DISPATCH();
        }

        TARGET(LOAD_CLOSURE) {
            OP(LOAD_CLOSURE, oparg);
            DISPATCH();
        }

        TARGET(LOAD_FAST_CHECK) {
            OP(LOAD_FAST_CHECK, oparg);
            DISPATCH();
        }

        TARGET(LOAD_FAST) {
            OP(LOAD_FAST, oparg);
            DISPATCH();
        }

        TARGET(LOAD_FAST_AND_CLEAR) {
            OP(LOAD_FAST_AND_CLEAR, oparg);
            DISPATCH();
        }

        TARGET(LOAD_CONST) {
            OP(LOAD_CONST, oparg);
            DISPATCH();
        }

        TARGET(STORE_FAST) {
            OP(STORE_FAST, oparg);
            DISPATCH();
        }

        TARGET(LOAD_FAST__LOAD_FAST) {
            OP(LOAD_FAST__LOAD_FAST, oparg, (oparg = (next_instr++)->op.arg));
            DISPATCH();
        }

        TARGET(LOAD_FAST__LOAD_CONST) {
            OP(LOAD_FAST__LOAD_CONST, oparg, (oparg = (next_instr++)->op.arg));
            DISPATCH();
        }

        TARGET(STORE_FAST__LOAD_FAST) {
            OP(STORE_FAST__LOAD_FAST, oparg, (oparg = (next_instr++)->op.arg));
            DISPATCH();
        }

        TARGET(STORE_FAST__STORE_FAST) {
            OP(STORE_FAST__STORE_FAST, oparg, (oparg = (next_instr++)->op.arg));
            DISPATCH();
        }

        TARGET(LOAD_CONST__LOAD_FAST) {
            OP(LOAD_CONST__LOAD_FAST, oparg, (oparg = (next_instr++)->op.arg));
            DISPATCH();
        }

        TARGET(POP_TOP) {
            OP(POP_TOP);
            DISPATCH();
        }

        TARGET(PUSH_NULL) {
            OP(PUSH_NULL);
            DISPATCH();
        }

        TARGET(END_FOR) {
            OP(END_FOR);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_END_FOR) {
            OP(INSTRUMENTED_END_FOR);
            DISPATCH();
        }

        TARGET(END_SEND) {
            OP(END_SEND);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_END_SEND) {
            OP(INSTRUMENTED_END_SEND);
            DISPATCH();
        }

        TARGET(UNARY_NEGATIVE) {
            OP(UNARY_NEGATIVE);
            DISPATCH();
        }

        TARGET(UNARY_NOT) {
            OP(UNARY_NOT);
            DISPATCH();
        }

        TARGET(UNARY_INVERT) {
            OP(UNARY_INVERT);
            DISPATCH();
        }

        TARGET(BINARY_OP_MULTIPLY_INT) {
            OP(BINARY_OP_MULTIPLY_INT);
            DISPATCH();
        }

        TARGET(BINARY_OP_MULTIPLY_FLOAT) {
            OP(BINARY_OP_MULTIPLY_FLOAT);
            DISPATCH();
        }

        TARGET(BINARY_OP_SUBTRACT_INT) {
            OP(BINARY_OP_SUBTRACT_INT);
            DISPATCH();
        }

        TARGET(BINARY_OP_SUBTRACT_FLOAT) {
            OP(BINARY_OP_SUBTRACT_FLOAT);
            DISPATCH();
        }

        TARGET(BINARY_OP_ADD_UNICODE) {
            OP(BINARY_OP_ADD_UNICODE);
            DISPATCH();
        }

        TARGET(BINARY_OP_INPLACE_ADD_UNICODE) {
            OP(BINARY_OP_INPLACE_ADD_UNICODE);
            DISPATCH();
        }

        TARGET(BINARY_OP_ADD_FLOAT) {
            OP(BINARY_OP_ADD_FLOAT);
            DISPATCH();
        }

        TARGET(BINARY_OP_ADD_INT) {
            OP(BINARY_OP_ADD_INT);
            DISPATCH();
        }

        TARGET(BINARY_SUBSCR) {
            OP(BINARY_SUBSCR);
            DISPATCH();
        }

        TARGET(BINARY_SLICE) {
            OP(BINARY_SLICE);
            DISPATCH();
        }

        TARGET(STORE_SLICE) {
            OP(STORE_SLICE);
            DISPATCH();
        }

        TARGET(BINARY_SUBSCR_LIST_INT) {
            OP(BINARY_SUBSCR_LIST_INT);
            DISPATCH();
        }

        TARGET(BINARY_SUBSCR_TUPLE_INT) {
            OP(BINARY_SUBSCR_TUPLE_INT);
            DISPATCH();
        }

        TARGET(BINARY_SUBSCR_DICT) {
            OP(BINARY_SUBSCR_DICT);
            DISPATCH();
        }

        TARGET(BINARY_SUBSCR_GETITEM) {
            OP(BINARY_SUBSCR_GETITEM);
            DISPATCH();
        }

        TARGET(LIST_APPEND) {
            OP(LIST_APPEND, oparg);
            DISPATCH();
        }

        TARGET(SET_ADD) {
            OP(SET_ADD, oparg);
            DISPATCH();
        }

        TARGET(STORE_SUBSCR) {
            OP(STORE_SUBSCR);
            DISPATCH();
        }

        TARGET(STORE_SUBSCR_LIST_INT) {
            OP(STORE_SUBSCR_LIST_INT);
            DISPATCH();
        }

        TARGET(STORE_SUBSCR_DICT) {
            OP(STORE_SUBSCR_DICT);
            DISPATCH();
        }

        TARGET(DELETE_SUBSCR) {
            OP(DELETE_SUBSCR);
            DISPATCH();
        }

        TARGET(CALL_INTRINSIC_1) {
            OP(CALL_INTRINSIC_1, oparg);
            DISPATCH();
        }

        TARGET(CALL_INTRINSIC_2) {
            OP(CALL_INTRINSIC_2, oparg);
            DISPATCH();
        }

        TARGET(RAISE_VARARGS) {
            OP(RAISE_VARARGS, oparg);
            DISPATCH();
        }

        TARGET(INTERPRETER_EXIT) {
            OP(INTERPRETER_EXIT);
            DISPATCH();
        }

        TARGET(RETURN_VALUE) {
            OP(RETURN_VALUE);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_RETURN_VALUE) {
            OP(INSTRUMENTED_RETURN_VALUE);
            DISPATCH();
        }

        TARGET(RETURN_CONST) {
            OP(RETURN_CONST, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_RETURN_CONST) {
            OP(INSTRUMENTED_RETURN_CONST, oparg);
            DISPATCH();
        }

        TARGET(GET_AITER) {
            OP(GET_AITER);
            DISPATCH();
        }

        TARGET(GET_ANEXT) {
            OP(GET_ANEXT);
            DISPATCH();
        }

        TARGET(GET_AWAITABLE) {
            OP(GET_AWAITABLE, oparg);
            DISPATCH();
        }

        TARGET(SEND) {
            OP(SEND, oparg);
            DISPATCH();
        }

        TARGET(SEND_GEN) {
            OP(SEND_GEN, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_YIELD_VALUE) {
            OP(INSTRUMENTED_YIELD_VALUE);
            DISPATCH();
        }

        TARGET(YIELD_VALUE) {
            OP(YIELD_VALUE);
            DISPATCH();
        }

        TARGET(POP_EXCEPT) {
            OP(POP_EXCEPT);
            DISPATCH();
        }

        TARGET(RERAISE) {
            OP(RERAISE, oparg);
            DISPATCH();
        }

        TARGET(END_ASYNC_FOR) {
            OP(END_ASYNC_FOR);
            DISPATCH();
        }

        TARGET(CLEANUP_THROW) {
            OP(CLEANUP_THROW);
            DISPATCH();
        }

        TARGET(LOAD_ASSERTION_ERROR) {
            OP(LOAD_ASSERTION_ERROR);
            DISPATCH();
        }

        TARGET(LOAD_BUILD_CLASS) {
            OP(LOAD_BUILD_CLASS);
            DISPATCH();
        }

        TARGET(STORE_NAME) {
            OP(STORE_NAME, oparg);
            DISPATCH();
        }

        TARGET(DELETE_NAME) {
            OP(DELETE_NAME, oparg);
            DISPATCH();
        }

        TARGET(UNPACK_SEQUENCE) {
            OP(UNPACK_SEQUENCE, oparg);
            DISPATCH();
        }

        TARGET(UNPACK_SEQUENCE_TWO_TUPLE) {
            OP(UNPACK_SEQUENCE_TWO_TUPLE, oparg);
            DISPATCH();
        }

        TARGET(UNPACK_SEQUENCE_TUPLE) {
            OP(UNPACK_SEQUENCE_TUPLE, oparg);
            DISPATCH();
        }

        TARGET(UNPACK_SEQUENCE_LIST) {
            OP(UNPACK_SEQUENCE_LIST, oparg);
            DISPATCH();
        }

        TARGET(UNPACK_EX) {
            OP(UNPACK_EX, oparg);
            DISPATCH();
        }

        TARGET(STORE_ATTR) {
            OP(STORE_ATTR, oparg);
            DISPATCH();
        }

        TARGET(DELETE_ATTR) {
            OP(DELETE_ATTR, oparg);
            DISPATCH();
        }

        TARGET(STORE_GLOBAL) {
            OP(STORE_GLOBAL, oparg);
            DISPATCH();
        }

        TARGET(DELETE_GLOBAL) {
            OP(DELETE_GLOBAL, oparg);
            DISPATCH();
        }

        TARGET(LOAD_LOCALS) {
            OP(LOAD_LOCALS);
            DISPATCH();
        }

        TARGET(LOAD_FROM_DICT_OR_GLOBALS) {
            OP(LOAD_FROM_DICT_OR_GLOBALS, oparg);
            DISPATCH();
        }

        TARGET(LOAD_NAME) {
            OP(LOAD_NAME, oparg);
            DISPATCH();
        }

        TARGET(LOAD_GLOBAL) {
            OP(LOAD_GLOBAL, oparg);
            DISPATCH();
        }

        TARGET(LOAD_GLOBAL_MODULE) {
            OP(LOAD_GLOBAL_MODULE, oparg);
            DISPATCH();
        }

        TARGET(LOAD_GLOBAL_BUILTIN) {
            OP(LOAD_GLOBAL_BUILTIN, oparg);
            DISPATCH();
        }

        TARGET(DELETE_FAST) {
            OP(DELETE_FAST, oparg);
            DISPATCH();
        }

        TARGET(MAKE_CELL) {
            OP(MAKE_CELL, oparg);
            DISPATCH();
        }

        TARGET(DELETE_DEREF) {
            OP(DELETE_DEREF, oparg);
            DISPATCH();
        }

        TARGET(LOAD_FROM_DICT_OR_DEREF) {
            OP(LOAD_FROM_DICT_OR_DEREF, oparg);
            DISPATCH();
        }

        TARGET(LOAD_DEREF) {
            OP(LOAD_DEREF, oparg);
            DISPATCH();
        }

        TARGET(STORE_DEREF) {
            OP(STORE_DEREF, oparg);
            DISPATCH();
        }

        TARGET(COPY_FREE_VARS) {
            OP(COPY_FREE_VARS, oparg);
            DISPATCH();
        }

        TARGET(BUILD_STRING) {
            OP(BUILD_STRING, oparg);
            DISPATCH();
        }

        TARGET(BUILD_TUPLE) {
            OP(BUILD_TUPLE, oparg);
            DISPATCH();
        }

        TARGET(BUILD_LIST) {
            OP(BUILD_LIST, oparg);
            DISPATCH();
        }

        TARGET(LIST_EXTEND) {
            OP(LIST_EXTEND, oparg);
            DISPATCH();
        }

        TARGET(SET_UPDATE) {
            OP(SET_UPDATE, oparg);
            DISPATCH();
        }

        TARGET(BUILD_SET) {
            OP(BUILD_SET, oparg);
            DISPATCH();
        }

        TARGET(BUILD_MAP) {
            OP(BUILD_MAP, oparg);
            DISPATCH();
        }

        TARGET(SETUP_ANNOTATIONS) {
            OP(SETUP_ANNOTATIONS);
            DISPATCH();
        }

        TARGET(BUILD_CONST_KEY_MAP) {
            OP(BUILD_CONST_KEY_MAP, oparg);
            DISPATCH();
        }

        TARGET(DICT_UPDATE) {
            OP(DICT_UPDATE, oparg);
            DISPATCH();
        }

        TARGET(DICT_MERGE) {
            OP(DICT_MERGE, oparg);
            DISPATCH();
        }

        TARGET(MAP_ADD) {
            OP(MAP_ADD, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_LOAD_SUPER_ATTR) {
            OP(INSTRUMENTED_LOAD_SUPER_ATTR, oparg);
            DISPATCH();
        }

        TARGET(LOAD_SUPER_ATTR) {
            OP(LOAD_SUPER_ATTR, oparg);
            DISPATCH();
        }

        TARGET(LOAD_SUPER_ATTR_ATTR) {
            OP(LOAD_SUPER_ATTR_ATTR, oparg);
            DISPATCH();
        }

        TARGET(LOAD_SUPER_ATTR_METHOD) {
            OP(LOAD_SUPER_ATTR_METHOD, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR) {
            OP(LOAD_ATTR, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_INSTANCE_VALUE) {
            OP(LOAD_ATTR_INSTANCE_VALUE, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_MODULE) {
            OP(LOAD_ATTR_MODULE, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_WITH_HINT) {
            OP(LOAD_ATTR_WITH_HINT, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_SLOT) {
            OP(LOAD_ATTR_SLOT, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_CLASS) {
            OP(LOAD_ATTR_CLASS, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_PROPERTY) {
            OP(LOAD_ATTR_PROPERTY, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN) {
            OP(LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN, oparg);
            DISPATCH();
        }

        TARGET(STORE_ATTR_INSTANCE_VALUE) {
            OP(STORE_ATTR_INSTANCE_VALUE);
            DISPATCH();
        }

        TARGET(STORE_ATTR_WITH_HINT) {
            OP(STORE_ATTR_WITH_HINT, oparg);
            DISPATCH();
        }

        TARGET(STORE_ATTR_SLOT) {
            OP(STORE_ATTR_SLOT);
            DISPATCH();
        }

        TARGET(COMPARE_OP) {
            OP(COMPARE_OP, oparg);
            DISPATCH();
        }

        TARGET(COMPARE_OP_FLOAT) {
            OP(COMPARE_OP_FLOAT, oparg);
            DISPATCH();
        }

        TARGET(COMPARE_OP_INT) {
            OP(COMPARE_OP_INT, oparg);
            DISPATCH();
        }

        TARGET(COMPARE_OP_STR) {
            OP(COMPARE_OP_STR, oparg);
            DISPATCH();
        }

        TARGET(IS_OP) {
            OP(IS_OP, oparg);
            DISPATCH();
        }

        TARGET(CONTAINS_OP) {
            OP(CONTAINS_OP, oparg);
            DISPATCH();
        }

        TARGET(CHECK_EG_MATCH) {
            OP(CHECK_EG_MATCH);
            DISPATCH();
        }

        TARGET(CHECK_EXC_MATCH) {
            OP(CHECK_EXC_MATCH);
            DISPATCH();
        }

        TARGET(IMPORT_NAME) {
            OP(IMPORT_NAME, oparg);
            DISPATCH();
        }

        TARGET(IMPORT_FROM) {
            OP(IMPORT_FROM, oparg);
            DISPATCH();
        }

        TARGET(JUMP_FORWARD) {
            OP(JUMP_FORWARD, oparg);
            DISPATCH();
        }

        TARGET(JUMP_BACKWARD) {
            OP(JUMP_BACKWARD, oparg);
            DISPATCH();
        }

        TARGET(POP_JUMP_IF_FALSE) {
            OP(POP_JUMP_IF_FALSE, oparg);
            DISPATCH();
        }

        TARGET(POP_JUMP_IF_TRUE) {
            OP(POP_JUMP_IF_TRUE, oparg);
            DISPATCH();
        }

        TARGET(POP_JUMP_IF_NOT_NONE) {
            OP(POP_JUMP_IF_NOT_NONE, oparg);
            DISPATCH();
        }

        TARGET(POP_JUMP_IF_NONE) {
            OP(POP_JUMP_IF_NONE, oparg);
            DISPATCH();
        }

        TARGET(JUMP_BACKWARD_NO_INTERRUPT) {
            OP(JUMP_BACKWARD_NO_INTERRUPT, oparg);
            DISPATCH();
        }

        TARGET(GET_LEN) {
            OP(GET_LEN);
            DISPATCH();
        }

        TARGET(MATCH_CLASS) {
            OP(MATCH_CLASS, oparg);
            DISPATCH();
        }

        TARGET(MATCH_MAPPING) {
            OP(MATCH_MAPPING);
            DISPATCH();
        }

        TARGET(MATCH_SEQUENCE) {
            OP(MATCH_SEQUENCE);
            DISPATCH();
        }

        TARGET(MATCH_KEYS) {
            OP(MATCH_KEYS);
            DISPATCH();
        }

        TARGET(GET_ITER) {
            OP(GET_ITER);
            DISPATCH();
        }

        TARGET(GET_YIELD_FROM_ITER) {
            OP(GET_YIELD_FROM_ITER);
            DISPATCH();
        }

        TARGET(FOR_ITER) {
            OP(FOR_ITER, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_FOR_ITER) {
            OP(INSTRUMENTED_FOR_ITER, oparg);
            DISPATCH();
        }

        TARGET(FOR_ITER_LIST) {
            OP(FOR_ITER_LIST, oparg);
            DISPATCH();
        }

        TARGET(FOR_ITER_TUPLE) {
            OP(FOR_ITER_TUPLE, oparg);
            DISPATCH();
        }

        TARGET(FOR_ITER_RANGE) {
            OP(FOR_ITER_RANGE, oparg);
            DISPATCH();
        }

        TARGET(FOR_ITER_GEN) {
            OP(FOR_ITER_GEN, oparg);
            DISPATCH();
        }

        TARGET(BEFORE_ASYNC_WITH) {
            OP(BEFORE_ASYNC_WITH);
            DISPATCH();
        }

        TARGET(BEFORE_WITH) {
            OP(BEFORE_WITH);
            DISPATCH();
        }

        TARGET(WITH_EXCEPT_START) {
            OP(WITH_EXCEPT_START);
            DISPATCH();
        }

        TARGET(PUSH_EXC_INFO) {
            OP(PUSH_EXC_INFO);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_METHOD_WITH_VALUES) {
            OP(LOAD_ATTR_METHOD_WITH_VALUES, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_METHOD_NO_DICT) {
            OP(LOAD_ATTR_METHOD_NO_DICT, oparg);
            DISPATCH();
        }

        TARGET(LOAD_ATTR_METHOD_LAZY_DICT) {
            OP(LOAD_ATTR_METHOD_LAZY_DICT, oparg);
            DISPATCH();
        }

        TARGET(KW_NAMES) {
            OP(KW_NAMES, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_CALL) {
            OP(INSTRUMENTED_CALL, oparg);
            DISPATCH();
        }

        TARGET(CALL) {
            OP(CALL, oparg);
            DISPATCH();
        }

        TARGET(CALL_BOUND_METHOD_EXACT_ARGS) {
            OP(CALL_BOUND_METHOD_EXACT_ARGS, oparg);
            DISPATCH();
        }

        TARGET(CALL_PY_EXACT_ARGS) {
            OP(CALL_PY_EXACT_ARGS, oparg);
            DISPATCH();
        }

        TARGET(CALL_PY_WITH_DEFAULTS) {
            OP(CALL_PY_WITH_DEFAULTS, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_TYPE_1) {
            OP(CALL_NO_KW_TYPE_1, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_STR_1) {
            OP(CALL_NO_KW_STR_1, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_TUPLE_1) {
            OP(CALL_NO_KW_TUPLE_1, oparg);
            DISPATCH();
        }

        TARGET(CALL_BUILTIN_CLASS) {
            OP(CALL_BUILTIN_CLASS, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_BUILTIN_O) {
            OP(CALL_NO_KW_BUILTIN_O, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_BUILTIN_FAST) {
            OP(CALL_NO_KW_BUILTIN_FAST, oparg);
            DISPATCH();
        }

        TARGET(CALL_BUILTIN_FAST_WITH_KEYWORDS) {
            OP(CALL_BUILTIN_FAST_WITH_KEYWORDS, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_LEN) {
            OP(CALL_NO_KW_LEN, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_ISINSTANCE) {
            OP(CALL_NO_KW_ISINSTANCE, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_LIST_APPEND) {
            OP(CALL_NO_KW_LIST_APPEND, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_METHOD_DESCRIPTOR_O) {
            OP(CALL_NO_KW_METHOD_DESCRIPTOR_O, oparg);
            DISPATCH();
        }

        TARGET(CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS) {
            OP(CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS) {
            OP(CALL_NO_KW_METHOD_DESCRIPTOR_NOARGS, oparg);
            DISPATCH();
        }

        TARGET(CALL_NO_KW_METHOD_DESCRIPTOR_FAST) {
            OP(CALL_NO_KW_METHOD_DESCRIPTOR_FAST, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_CALL_FUNCTION_EX) {
            OP(INSTRUMENTED_CALL_FUNCTION_EX);
            DISPATCH();
        }

        TARGET(CALL_FUNCTION_EX) {
            OP(CALL_FUNCTION_EX, oparg);
            DISPATCH();
        }

        TARGET(MAKE_FUNCTION) {
            OP(MAKE_FUNCTION, oparg);
            DISPATCH();
        }

        TARGET(RETURN_GENERATOR) {
            OP(RETURN_GENERATOR);
            DISPATCH();
        }

        TARGET(BUILD_SLICE) {
            OP(BUILD_SLICE, oparg);
            DISPATCH();
        }

        TARGET(FORMAT_VALUE) {
            OP(FORMAT_VALUE, oparg);
            DISPATCH();
        }

        TARGET(COPY) {
            OP(COPY, oparg);
            DISPATCH();
        }

        TARGET(BINARY_OP) {
            OP(BINARY_OP, oparg);
            DISPATCH();
        }

        TARGET(SWAP) {
            OP(SWAP, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_INSTRUCTION) {
            OP(INSTRUMENTED_INSTRUCTION);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_JUMP_FORWARD) {
            OP(INSTRUMENTED_JUMP_FORWARD, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_JUMP_BACKWARD) {
            OP(INSTRUMENTED_JUMP_BACKWARD, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_POP_JUMP_IF_TRUE) {
            OP(INSTRUMENTED_POP_JUMP_IF_TRUE, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_POP_JUMP_IF_FALSE) {
            OP(INSTRUMENTED_POP_JUMP_IF_FALSE, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_POP_JUMP_IF_NONE) {
            OP(INSTRUMENTED_POP_JUMP_IF_NONE, oparg);
            DISPATCH();
        }

        TARGET(INSTRUMENTED_POP_JUMP_IF_NOT_NONE) {
            OP(INSTRUMENTED_POP_JUMP_IF_NOT_NONE, oparg);
            DISPATCH();
        }

        TARGET(EXTENDED_ARG) {
            OP(EXTENDED_ARG, oparg);
            DISPATCH();
        }

        TARGET(CACHE) {
            OP(CACHE);
            DISPATCH();
        }

        TARGET(RESERVED) {
            OP(RESERVED);
            DISPATCH();
        }
